In [51]:
from pathlib import Path
import pandas as pd
import geopandas as gp

OUTPUT = Path.cwd().parents[0] / "Output"
df = pd.read_csv(Path.cwd().parents[0] /"CSV"/"HLL"/"hashtag_latlng.csv",usecols = [0,1,2,3,4,5])
df

,user_hll,post_hll,date_hll,latitude,longitude,hashtag
0,\x128b7fb4d8fa14cea9445b4a3eaa08e4f50475,\x128b7f81d7005ab2a56ed582a2d6fd191e3536340773...,\x128b7fcb2e51821af86f9a019032cc0076d0dc39c8c9...,28.017169,1.664273,afrique
1,\x128b7f9f066fa6767e1b74,\x128b7f1d27a3bfaaf36ec3,\x128b7fe6aa4fc35137c16a,28.017169,1.664273,alger
2,\x128b7fff8583ff68e4d52c,\x128b7fa09e9b1ed7ebcf78aad378f76965dcdc,\x128b7f9f2a0a9344c7fd84,28.017169,1.664273,algeria
3,\x128b7fff8583ff68e4d52c,\x128b7f3c1b3840c027340e,\x128b7f56d8c1622eb9ba87,28.017169,1.664273,algerian
4,\x128b7fff8583ff68e4d52c,\x128b7fa09e9b1ed7ebcf78aad378f76965dcdcdb1591...,\x128b7f9f2a0a9344c7fd84,28.017169,1.664273,algerie
...,...,...,...,...,...,...
211547,\x128b7f118884db03390fed,\x128b7f03feddaf4ede1ac3,\x128b7f4b1278ad70c8792b,70.071230,19.437217,refugeeswelcome
211548,\x128b7fc0511d735a360ec4,\x128b7fc4a6567543b7ba85,\x128b7f4c59adaf6af1bdbc,70.266777,21.816807,asylchaos
211549,\x128b7f3f848baabe36a655,\x128b7f697b9c7e91df9fde,\x128b7f2cbcef3f1beacdc2,70.326849,30.646058,herecomesthesun
211550,\x128b7f3f848baabe36a655,\x128b7f697b9c7e91df9fde,\x128b7f2cbcef3f1beacdc2,70.326849,30.646058,migrants
211551,\x128b7ff9d85f7adf62ac10,\x128b7f8ed8192757b191d0,\x128b7f91ada0f456cbfd1b,70.715060,23.454052,asylbarn

In [64]:
df['post_hll'] = df['post_hll'].apply(lambda x: x[2:])
df['date_hll'] = df['date_hll'].apply(lambda x: x[2:])
df['user_hll'] = df['user_hll'].apply(lambda x: x[2:])
df

,user_hll,post_hll,date_hll,latitude,longitude,hashtag
0,128b7fb4d8fa14cea9445b4a3eaa08e4f50475,128b7f81d7005ab2a56ed582a2d6fd191e353634077393...,128b7fcb2e51821af86f9a019032cc0076d0dc39c8c9d3...,28.017169,1.664273,afrique
1,128b7f9f066fa6767e1b74,128b7f1d27a3bfaaf36ec3,128b7fe6aa4fc35137c16a,28.017169,1.664273,alger
2,128b7fff8583ff68e4d52c,128b7fa09e9b1ed7ebcf78aad378f76965dcdc,128b7f9f2a0a9344c7fd84,28.017169,1.664273,algeria
3,128b7fff8583ff68e4d52c,128b7f3c1b3840c027340e,128b7f56d8c1622eb9ba87,28.017169,1.664273,algerian
4,128b7fff8583ff68e4d52c,128b7fa09e9b1ed7ebcf78aad378f76965dcdcdb15916a...,128b7f9f2a0a9344c7fd84,28.017169,1.664273,algerie
...,...,...,...,...,...,...
211547,128b7f118884db03390fed,128b7f03feddaf4ede1ac3,128b7f4b1278ad70c8792b,70.071230,19.437217,refugeeswelcome
211548,128b7fc0511d735a360ec4,128b7fc4a6567543b7ba85,128b7f4c59adaf6af1bdbc,70.266777,21.816807,asylchaos
211549,128b7f3f848baabe36a655,128b7f697b9c7e91df9fde,128b7f2cbcef3f1beacdc2,70.326849,30.646058,herecomesthesun
211550,128b7f3f848baabe36a655,128b7f697b9c7e91df9fde,128b7f2cbcef3f1beacdc2,70.326849,30.646058,migrants
211551,128b7ff9d85f7adf62ac10,128b7f8ed8192757b191d0,128b7f91ada0f456cbfd1b,70.715060,23.454052,asylbarn

In [65]:
mask = "hashtag == 'refugees' "
df_refugees = df.query(mask)
df_refugees.drop(columns = ['user_hll', 'date_hll'],inplace = True)
df_refugees

/home/sagnik/miniconda3/envs/workshop_env/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,post_hll,latitude,longitude,hashtag
128,128b7fb0a4c7eeb9d9ba77ddcee864ad217fd41734e241...,28.017169,1.664273,refugees
226,128b7f9dc5232dbd5704aa598ceef859815cf976c21088...,28.326263,-9.082743,refugees
239,128b7f5b9c9bb7032cd110,33.133300,11.216700,refugees
431,128b7f838d45894abb2b87934cb916616adf95a2b00127...,33.894928,9.556354,refugees
533,128b7fe52341cdde638234,35.141912,24.596244,refugees
...,...,...,...,...
211437,128b7f75b58ceed3657d8f,66.439735,14.360560,refugees
211455,128b7f4eb61f291c5b3bbf,66.669948,26.031108,refugees
211477,128b7f30a4334fdc15f25c,67.295171,14.440035,refugees
211484,128b7fd261434fd4cc0bee,67.516345,13.694598,refugees
211528,128b7f8f94ddf02c5794b1,69.504585,29.727145,refugees

In [66]:
mask = "hashtag == 'migrants' "
df_migrants = df.query(mask)
df_migrants.drop(columns = ['user_hll', 'date_hll'],inplace = True)
df_migrants

/home/sagnik/miniconda3/envs/workshop_env/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,post_hll,latitude,longitude,hashtag
90,128b7f81d7005ab2a56ed582a2d6fd191e3536850ad600...,28.017169,1.664273,migrants
216,128b7fa8e1fcd6de7c960cc74b7e2577aab652e37d19c6...,28.326263,-9.082743,migrants
238,128b7f5b9c9bb7032cd110,33.133300,11.216700,migrants
390,128b7f8def0010de6b5d8e8ed4b642ed1b01d98eda55bd...,33.894928,9.556354,migrants
574,128b7f8b06ac72c87bc19f974e00305aa255649cfe309b...,35.248824,24.913154,migrants
...,...,...,...,...
211203,128b7f2ac026502988616768e821e5cc7ab291,63.409964,10.365963,migrants
211344,128b7f4af5922a35c53943,64.883749,25.377699,migrants
211448,128b7fb20184f57e22397f2bdf559ed857f453,66.669948,26.031108,migrants
211513,128b7f8aaf01f44e1fbab9da45ded99a559b75,69.390384,12.274479,migrants
211550,128b7f697b9c7e91df9fde,70.326849,30.646058,migrants

In [67]:
mask = "hashtag == 'refugeeswelcome' "
df_refugeeswelcome = df.query(mask)
df_refugeeswelcome.drop(columns = ['user_hll', 'date_hll'],inplace = True)
df_refugeeswelcome

/home/sagnik/miniconda3/envs/workshop_env/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,post_hll,latitude,longitude,hashtag
129,128b7fa09e9b1ed7ebcf78aad378f76965dcdcea90b6b0...,28.017169,1.664273,refugeeswelcome
433,128b7fe6a3cdd1b3c6d993fb9979b56c9b64dc6a72580d...,33.894928,9.556354,refugeeswelcome
522,128b7f94c2a4cbedf17029,35.000000,18.000000,refugeeswelcome
580,128b7f3c7a9985723106d0,35.248824,24.913154,refugeeswelcome
602,128b7fa81dd0a12d2866c5,35.271078,25.123058,refugeeswelcome
...,...,...,...,...
211398,128b7f9f08b4c3a34828502c64d212d60a97dc,65.204326,25.683516,refugeeswelcome
211431,128b7fc901e22f4a432017,65.691135,22.229912,refugeeswelcome
211529,128b7f980b092b7a20d3d8b04c3125e8455cc0,69.504585,29.727145,refugeeswelcome
211543,128b7fb3b6bdf43ad185297ab184d73533073c,69.710402,18.925811,refugeeswelcome
211547,128b7f03feddaf4ede1ac3,70.071230,19.437217,refugeeswelcome

In [55]:
type(df_migrants['post_hll'].values[0])

str

In [72]:
from python_hll.hll import HLL
from python_hll.util import NumberUtil

def hll_from_byte(hll_set):
    """Return HLL set from binary representation"""
     
    return HLL.from_bytes(
        NumberUtil.from_hex(
            hll_set, 0, len(hll_set)))



def union_hll(hll, hll2):
    """Union of two HLL sets. The first HLL set will be modified in-place."""
    hll.union(hll2)
    
def union_all_hll(hll_series,cardinality = True):
    """HLL Union and (optional) cardinality estimation from series of hll sets

        Args:
        hll_series: Indexed series (bins) of hll sets. 
        cardinality: If True, returns cardinality (counts). Otherwise,
            the unioned hll set will be returned.
    """
    
    hll_set = None
    for hll_set_str in hll_series.values.tolist():
        if hll_set is None:
            # set first hll set
            hll_set = hll_from_byte(hll_set_str)
            continue
        hll_set2 = hll_from_byte(hll_set_str)
        union_hll(hll_set, hll_set2)
    return hll_set.cardinality()

In [74]:
dfs = {"migrants" : df_migrants,
         "refugees": df_refugees,
         "refugeeswelcome" :df_refugeeswelcome
        }

posts_total = {}
for hashtag, dfs in dfs.items():
    # drop bins with no values
    cardinality_total = union_all_hll(
        dfs["post_hll"].dropna())
    posts_total[hashtag] = cardinality_total
    print(
        f"{posts_total[hashtag]} distinct posts "
        f"had {hashtag.upper()}")

12301 distinct posts had MIGRANTS
16893 distinct posts had REFUGEES
12252 distinct posts had REFUGEESWELCOME

In [78]:
union_mig_ref = pd.concat([df_migrants, df_refugees])
union_mig_rw = pd.concat([df_migrants, df_refugeeswelcome])
union_ref_re = pd.concat([df_refugeeswelcome, df_refugees])


dfs = {
    "migrants_refugeeswelcome": union_mig_rw,
    "migrants_refugees": union_mig_ref,
    "refugees_refugeeswelcome": union_ref_re
}
distinct_common = {}
for hashtag_set, dfs in dfs.items():
    cardinality = union_all_hll(
        dfs["post_hll"].dropna())
    distinct_common[hashtag_set] = cardinality
    print(
        f"{distinct_common[hashtag_set]} distinct total posts "
        f"who posted with either {hashtag_set.split('_')[0]} "
        f"or {hashtag_set.split('_')[1]} (union)")

24236 distinct total posts who posted with either migrants or refugeeswelcome (union)
28112 distinct total posts who posted with either migrants or refugees (union)
27708 distinct total posts who posted with either refugees or refugeeswelcome (union)

In [82]:
distinct_intersection = {}
for a, b in [("migrants", "refugeeswelcome"), ("migrants", "refugees"), ("refugees", "refugeeswelcome")]:
    a_total = posts_total[a]
    b_total = posts_total[b]
    common_ref = f'{a}_{b}'
    intersection_count = a_total + b_total - distinct_common[common_ref]
    distinct_intersection[common_ref] = intersection_count
    print(
        f"{distinct_intersection[common_ref]} distinct posts "
        f"with hashtags from {a} and {b} (intersection)")

317 distinct posts with hashtags from migrants and refugeeswelcome (intersection)
1082 distinct posts with hashtags from migrants and refugees (intersection)
1437 distinct posts with hashtags from refugees and refugeeswelcome (intersection)

In [84]:
union_de_fr_uk = pd.concat(
    [df_migrants, df_refugees, df_refugeeswelcome])
cardinality = union_all_hll(
    union_de_fr_uk["post_hll"].dropna())
union_count_all = cardinality
union_count_all

39115

In [85]:
hashtag_a = "migrants"
hashtag_b = "refugees"
hashtag_c = "refugeeswelcome"


intersection_count_all = union_count_all - \
    posts_total[hashtag_a] - \
    posts_total[hashtag_b] - \
    posts_total[hashtag_c] + \
    distinct_intersection[f'{hashtag_a}_{hashtag_b}'] + \
    distinct_intersection[f'{hashtag_a}_{hashtag_c}'] + \
    distinct_intersection[f'{hashtag_b}_{hashtag_c}']
    
print(intersection_count_all)

505